
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDA6T90oZ6MEEQ7E_dU5ZLYx8A__7ayY',
    appId: '1:15940837559:web:ac893d3cd8dd9ac4fd6d32',
    messagingSenderId: '15940837559',
    projectId: 'baby-sitter-cd7a5',
    authDomain: 'baby-sitter-cd7a5.firebaseapp.com',
    storageBucket: 'baby-sitter-cd7a5.appspot.com',
    measurementId: 'G-7V8ZN494N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo1v7SDrzf-iJ4peR9XuE-4r7IGHDopis',
    appId: '1:15940837559:android:07cb9105c91759c5fd6d32',
    messagingSenderId: '15940837559',
    projectId: 'baby-sitter-cd7a5',
    storageBucket: 'baby-sitter-cd7a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqr1ik1OCHzHC893GQLwOIDL-0tS1arI8',
    appId: '1:15940837559:ios:8c8fc47902d84841fd6d32',
    messagingSenderId: '15940837559',
    projectId: 'baby-sitter-cd7a5',
    storageBucket: 'baby-sitter-cd7a5.appspot.com',
    iosBundleId: 'com.example.babysitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqr1ik1OCHzHC893GQLwOIDL-0tS1arI8',
    appId: '1:15940837559:ios:28119179cf35a837fd6d32',
    messagingSenderId: '15940837559',
    projectId: 'baby-sitter-cd7a5',
    storageBucket: 'baby-sitter-cd7a5.appspot.com',
    iosBundleId: 'com.example.babysitter.RunnerTests',
  );
}
